# Generated by Django 3.0.8 on 2020-08-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200808_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img', verbose_name='Изображение')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.Article')),
            ],
        ),
    ]
