# Generated by Django 3.0.8 on 2020-08-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Article',
            new_name='article',
        ),
    ]
