# Generated by Django 3.0.8 on 2020-08-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200816_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='article1',
            new_name='articl',
        ),
    ]
