# Generated by Django 3.0.8 on 2020-08-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200816_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='articl',
            new_name='article',
        ),
    ]
